package com.springmvc.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public UserMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nickName is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nickName is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nickName =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nickName <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nickName >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nickName >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nickName <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nickName <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nickName like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nickName not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("nickName in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("nickName not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nickName between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nickName not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("realName is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("realName is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("realName =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("realName <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("realName >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("realName >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("realName <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("realName <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("realName like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("realName not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("realName in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("realName not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("realName between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("realName not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andIdCardNoIsNull() {
            addCriterion("idCardNo is null");
            return (Criteria) this;
        }

        public Criteria andIdCardNoIsNotNull() {
            addCriterion("idCardNo is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardNoEqualTo(String value) {
            addCriterion("idCardNo =", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotEqualTo(String value) {
            addCriterion("idCardNo <>", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoGreaterThan(String value) {
            addCriterion("idCardNo >", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("idCardNo >=", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoLessThan(String value) {
            addCriterion("idCardNo <", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoLessThanOrEqualTo(String value) {
            addCriterion("idCardNo <=", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoLike(String value) {
            addCriterion("idCardNo like", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotLike(String value) {
            addCriterion("idCardNo not like", value, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoIn(List<String> values) {
            addCriterion("idCardNo in", values, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotIn(List<String> values) {
            addCriterion("idCardNo not in", values, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoBetween(String value1, String value2) {
            addCriterion("idCardNo between", value1, value2, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardNoNotBetween(String value1, String value2) {
            addCriterion("idCardNo not between", value1, value2, "idCardNo");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("passwd is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("passwd is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("passwd =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("passwd <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("passwd >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("passwd >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("passwd <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("passwd <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("passwd like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("passwd not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("passwd in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("passwd not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("passwd between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("passwd not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPayPasswordIsNull() {
            addCriterion("payPassword is null");
            return (Criteria) this;
        }

        public Criteria andPayPasswordIsNotNull() {
            addCriterion("payPassword is not null");
            return (Criteria) this;
        }

        public Criteria andPayPasswordEqualTo(String value) {
            addCriterion("payPassword =", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotEqualTo(String value) {
            addCriterion("payPassword <>", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordGreaterThan(String value) {
            addCriterion("payPassword >", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("payPassword >=", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordLessThan(String value) {
            addCriterion("payPassword <", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordLessThanOrEqualTo(String value) {
            addCriterion("payPassword <=", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordLike(String value) {
            addCriterion("payPassword like", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotLike(String value) {
            addCriterion("payPassword not like", value, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordIn(List<String> values) {
            addCriterion("payPassword in", values, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotIn(List<String> values) {
            addCriterion("payPassword not in", values, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordBetween(String value1, String value2) {
            addCriterion("payPassword between", value1, value2, "payPassword");
            return (Criteria) this;
        }

        public Criteria andPayPasswordNotBetween(String value1, String value2) {
            addCriterion("payPassword not between", value1, value2, "payPassword");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("registerTime is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("registerTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("registerTime =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("registerTime <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("registerTime >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("registerTime >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("registerTime <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("registerTime <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("registerTime in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("registerTime not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("registerTime between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("registerTime not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRolesIsNull() {
            addCriterion("roles is null");
            return (Criteria) this;
        }

        public Criteria andRolesIsNotNull() {
            addCriterion("roles is not null");
            return (Criteria) this;
        }

        public Criteria andRolesEqualTo(Short value) {
            addCriterion("roles =", value, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesNotEqualTo(Short value) {
            addCriterion("roles <>", value, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesGreaterThan(Short value) {
            addCriterion("roles >", value, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesGreaterThanOrEqualTo(Short value) {
            addCriterion("roles >=", value, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesLessThan(Short value) {
            addCriterion("roles <", value, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesLessThanOrEqualTo(Short value) {
            addCriterion("roles <=", value, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesIn(List<Short> values) {
            addCriterion("roles in", values, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesNotIn(List<Short> values) {
            addCriterion("roles not in", values, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesBetween(Short value1, Short value2) {
            addCriterion("roles between", value1, value2, "roles");
            return (Criteria) this;
        }

        public Criteria andRolesNotBetween(Short value1, Short value2) {
            addCriterion("roles not between", value1, value2, "roles");
            return (Criteria) this;
        }

        public Criteria andCashIsNull() {
            addCriterion("cash is null");
            return (Criteria) this;
        }

        public Criteria andCashIsNotNull() {
            addCriterion("cash is not null");
            return (Criteria) this;
        }

        public Criteria andCashEqualTo(BigDecimal value) {
            addCriterion("cash =", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashNotEqualTo(BigDecimal value) {
            addCriterion("cash <>", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashGreaterThan(BigDecimal value) {
            addCriterion("cash >", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cash >=", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashLessThan(BigDecimal value) {
            addCriterion("cash <", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cash <=", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashIn(List<BigDecimal> values) {
            addCriterion("cash in", values, "cash");
            return (Criteria) this;
        }

        public Criteria andCashNotIn(List<BigDecimal> values) {
            addCriterion("cash not in", values, "cash");
            return (Criteria) this;
        }

        public Criteria andCashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash between", value1, value2, "cash");
            return (Criteria) this;
        }

        public Criteria andCashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash not between", value1, value2, "cash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashIsNull() {
            addCriterion("frozenWithDrawCash is null");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashIsNotNull() {
            addCriterion("frozenWithDrawCash is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashEqualTo(BigDecimal value) {
            addCriterion("frozenWithDrawCash =", value, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashNotEqualTo(BigDecimal value) {
            addCriterion("frozenWithDrawCash <>", value, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashGreaterThan(BigDecimal value) {
            addCriterion("frozenWithDrawCash >", value, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozenWithDrawCash >=", value, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashLessThan(BigDecimal value) {
            addCriterion("frozenWithDrawCash <", value, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozenWithDrawCash <=", value, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashIn(List<BigDecimal> values) {
            addCriterion("frozenWithDrawCash in", values, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashNotIn(List<BigDecimal> values) {
            addCriterion("frozenWithDrawCash not in", values, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozenWithDrawCash between", value1, value2, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenWithDrawCashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozenWithDrawCash not between", value1, value2, "frozenWithDrawCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashIsNull() {
            addCriterion("frozenBiddingCash is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashIsNotNull() {
            addCriterion("frozenBiddingCash is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashEqualTo(BigDecimal value) {
            addCriterion("frozenBiddingCash =", value, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashNotEqualTo(BigDecimal value) {
            addCriterion("frozenBiddingCash <>", value, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashGreaterThan(BigDecimal value) {
            addCriterion("frozenBiddingCash >", value, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozenBiddingCash >=", value, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashLessThan(BigDecimal value) {
            addCriterion("frozenBiddingCash <", value, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozenBiddingCash <=", value, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashIn(List<BigDecimal> values) {
            addCriterion("frozenBiddingCash in", values, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashNotIn(List<BigDecimal> values) {
            addCriterion("frozenBiddingCash not in", values, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozenBiddingCash between", value1, value2, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andFrozenBiddingCashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozenBiddingCash not between", value1, value2, "frozenBiddingCash");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitIsNull() {
            addCriterion("idVerifyLimit is null");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitIsNotNull() {
            addCriterion("idVerifyLimit is not null");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitEqualTo(Short value) {
            addCriterion("idVerifyLimit =", value, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitNotEqualTo(Short value) {
            addCriterion("idVerifyLimit <>", value, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitGreaterThan(Short value) {
            addCriterion("idVerifyLimit >", value, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitGreaterThanOrEqualTo(Short value) {
            addCriterion("idVerifyLimit >=", value, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitLessThan(Short value) {
            addCriterion("idVerifyLimit <", value, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitLessThanOrEqualTo(Short value) {
            addCriterion("idVerifyLimit <=", value, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitIn(List<Short> values) {
            addCriterion("idVerifyLimit in", values, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitNotIn(List<Short> values) {
            addCriterion("idVerifyLimit not in", values, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitBetween(Short value1, Short value2) {
            addCriterion("idVerifyLimit between", value1, value2, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andIdVerifyLimitNotBetween(Short value1, Short value2) {
            addCriterion("idVerifyLimit not between", value1, value2, "idVerifyLimit");
            return (Criteria) this;
        }

        public Criteria andPortraitIsNull() {
            addCriterion("portrait is null");
            return (Criteria) this;
        }

        public Criteria andPortraitIsNotNull() {
            addCriterion("portrait is not null");
            return (Criteria) this;
        }

        public Criteria andPortraitEqualTo(Integer value) {
            addCriterion("portrait =", value, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitNotEqualTo(Integer value) {
            addCriterion("portrait <>", value, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitGreaterThan(Integer value) {
            addCriterion("portrait >", value, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitGreaterThanOrEqualTo(Integer value) {
            addCriterion("portrait >=", value, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitLessThan(Integer value) {
            addCriterion("portrait <", value, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitLessThanOrEqualTo(Integer value) {
            addCriterion("portrait <=", value, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitIn(List<Integer> values) {
            addCriterion("portrait in", values, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitNotIn(List<Integer> values) {
            addCriterion("portrait not in", values, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitBetween(Integer value1, Integer value2) {
            addCriterion("portrait between", value1, value2, "portrait");
            return (Criteria) this;
        }

        public Criteria andPortraitNotBetween(Integer value1, Integer value2) {
            addCriterion("portrait not between", value1, value2, "portrait");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andForbidStatusIsNull() {
            addCriterion("forbidStatus is null");
            return (Criteria) this;
        }

        public Criteria andForbidStatusIsNotNull() {
            addCriterion("forbidStatus is not null");
            return (Criteria) this;
        }

        public Criteria andForbidStatusEqualTo(Short value) {
            addCriterion("forbidStatus =", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusNotEqualTo(Short value) {
            addCriterion("forbidStatus <>", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusGreaterThan(Short value) {
            addCriterion("forbidStatus >", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("forbidStatus >=", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusLessThan(Short value) {
            addCriterion("forbidStatus <", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusLessThanOrEqualTo(Short value) {
            addCriterion("forbidStatus <=", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusIn(List<Short> values) {
            addCriterion("forbidStatus in", values, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusNotIn(List<Short> values) {
            addCriterion("forbidStatus not in", values, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusBetween(Short value1, Short value2) {
            addCriterion("forbidStatus between", value1, value2, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusNotBetween(Short value1, Short value2) {
            addCriterion("forbidStatus not between", value1, value2, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityIsNull() {
            addCriterion("albumCapacity is null");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityIsNotNull() {
            addCriterion("albumCapacity is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityEqualTo(Short value) {
            addCriterion("albumCapacity =", value, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityNotEqualTo(Short value) {
            addCriterion("albumCapacity <>", value, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityGreaterThan(Short value) {
            addCriterion("albumCapacity >", value, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityGreaterThanOrEqualTo(Short value) {
            addCriterion("albumCapacity >=", value, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityLessThan(Short value) {
            addCriterion("albumCapacity <", value, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityLessThanOrEqualTo(Short value) {
            addCriterion("albumCapacity <=", value, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityIn(List<Short> values) {
            addCriterion("albumCapacity in", values, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityNotIn(List<Short> values) {
            addCriterion("albumCapacity not in", values, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityBetween(Short value1, Short value2) {
            addCriterion("albumCapacity between", value1, value2, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andAlbumCapacityNotBetween(Short value1, Short value2) {
            addCriterion("albumCapacity not between", value1, value2, "albumCapacity");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIsNull() {
            addCriterion("securityLevel is null");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIsNotNull() {
            addCriterion("securityLevel is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelEqualTo(Short value) {
            addCriterion("securityLevel =", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotEqualTo(Short value) {
            addCriterion("securityLevel <>", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelGreaterThan(Short value) {
            addCriterion("securityLevel >", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelGreaterThanOrEqualTo(Short value) {
            addCriterion("securityLevel >=", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelLessThan(Short value) {
            addCriterion("securityLevel <", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelLessThanOrEqualTo(Short value) {
            addCriterion("securityLevel <=", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIn(List<Short> values) {
            addCriterion("securityLevel in", values, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotIn(List<Short> values) {
            addCriterion("securityLevel not in", values, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelBetween(Short value1, Short value2) {
            addCriterion("securityLevel between", value1, value2, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotBetween(Short value1, Short value2) {
            addCriterion("securityLevel not between", value1, value2, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdIsNull() {
            addCriterion("weiboUId is null");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdIsNotNull() {
            addCriterion("weiboUId is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdEqualTo(String value) {
            addCriterion("weiboUId =", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotEqualTo(String value) {
            addCriterion("weiboUId <>", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdGreaterThan(String value) {
            addCriterion("weiboUId >", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdGreaterThanOrEqualTo(String value) {
            addCriterion("weiboUId >=", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdLessThan(String value) {
            addCriterion("weiboUId <", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdLessThanOrEqualTo(String value) {
            addCriterion("weiboUId <=", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdLike(String value) {
            addCriterion("weiboUId like", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotLike(String value) {
            addCriterion("weiboUId not like", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdIn(List<String> values) {
            addCriterion("weiboUId in", values, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotIn(List<String> values) {
            addCriterion("weiboUId not in", values, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdBetween(String value1, String value2) {
            addCriterion("weiboUId between", value1, value2, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotBetween(String value1, String value2) {
            addCriterion("weiboUId not between", value1, value2, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenIsNull() {
            addCriterion("weiboAccessToken is null");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenIsNotNull() {
            addCriterion("weiboAccessToken is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenEqualTo(String value) {
            addCriterion("weiboAccessToken =", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotEqualTo(String value) {
            addCriterion("weiboAccessToken <>", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenGreaterThan(String value) {
            addCriterion("weiboAccessToken >", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("weiboAccessToken >=", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenLessThan(String value) {
            addCriterion("weiboAccessToken <", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("weiboAccessToken <=", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenLike(String value) {
            addCriterion("weiboAccessToken like", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotLike(String value) {
            addCriterion("weiboAccessToken not like", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenIn(List<String> values) {
            addCriterion("weiboAccessToken in", values, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotIn(List<String> values) {
            addCriterion("weiboAccessToken not in", values, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenBetween(String value1, String value2) {
            addCriterion("weiboAccessToken between", value1, value2, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotBetween(String value1, String value2) {
            addCriterion("weiboAccessToken not between", value1, value2, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqUIdIsNull() {
            addCriterion("qqUId is null");
            return (Criteria) this;
        }

        public Criteria andQqUIdIsNotNull() {
            addCriterion("qqUId is not null");
            return (Criteria) this;
        }

        public Criteria andQqUIdEqualTo(String value) {
            addCriterion("qqUId =", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotEqualTo(String value) {
            addCriterion("qqUId <>", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdGreaterThan(String value) {
            addCriterion("qqUId >", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdGreaterThanOrEqualTo(String value) {
            addCriterion("qqUId >=", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdLessThan(String value) {
            addCriterion("qqUId <", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdLessThanOrEqualTo(String value) {
            addCriterion("qqUId <=", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdLike(String value) {
            addCriterion("qqUId like", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotLike(String value) {
            addCriterion("qqUId not like", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdIn(List<String> values) {
            addCriterion("qqUId in", values, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotIn(List<String> values) {
            addCriterion("qqUId not in", values, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdBetween(String value1, String value2) {
            addCriterion("qqUId between", value1, value2, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotBetween(String value1, String value2) {
            addCriterion("qqUId not between", value1, value2, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIsNull() {
            addCriterion("qqAccessToken is null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIsNotNull() {
            addCriterion("qqAccessToken is not null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenEqualTo(String value) {
            addCriterion("qqAccessToken =", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotEqualTo(String value) {
            addCriterion("qqAccessToken <>", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenGreaterThan(String value) {
            addCriterion("qqAccessToken >", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("qqAccessToken >=", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLessThan(String value) {
            addCriterion("qqAccessToken <", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("qqAccessToken <=", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLike(String value) {
            addCriterion("qqAccessToken like", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotLike(String value) {
            addCriterion("qqAccessToken not like", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIn(List<String> values) {
            addCriterion("qqAccessToken in", values, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotIn(List<String> values) {
            addCriterion("qqAccessToken not in", values, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenBetween(String value1, String value2) {
            addCriterion("qqAccessToken between", value1, value2, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotBetween(String value1, String value2) {
            addCriterion("qqAccessToken not between", value1, value2, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andOriginIsNull() {
            addCriterion("origin is null");
            return (Criteria) this;
        }

        public Criteria andOriginIsNotNull() {
            addCriterion("origin is not null");
            return (Criteria) this;
        }

        public Criteria andOriginEqualTo(Short value) {
            addCriterion("origin =", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotEqualTo(Short value) {
            addCriterion("origin <>", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThan(Short value) {
            addCriterion("origin >", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginGreaterThanOrEqualTo(Short value) {
            addCriterion("origin >=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThan(Short value) {
            addCriterion("origin <", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginLessThanOrEqualTo(Short value) {
            addCriterion("origin <=", value, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginIn(List<Short> values) {
            addCriterion("origin in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotIn(List<Short> values) {
            addCriterion("origin not in", values, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginBetween(Short value1, Short value2) {
            addCriterion("origin between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andOriginNotBetween(Short value1, Short value2) {
            addCriterion("origin not between", value1, value2, "origin");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staffId is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staffId is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Integer value) {
            addCriterion("staffId =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Integer value) {
            addCriterion("staffId <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Integer value) {
            addCriterion("staffId >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staffId >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Integer value) {
            addCriterion("staffId <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
            addCriterion("staffId <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Integer> values) {
            addCriterion("staffId in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Integer> values) {
            addCriterion("staffId not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Integer value1, Integer value2) {
            addCriterion("staffId between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staffId not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("userCode is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("userCode is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("userCode =", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("userCode <>", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("userCode >", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("userCode >=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("userCode <", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("userCode <=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("userCode like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("userCode not like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeIn(List<String> values) {
            addCriterion("userCode in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotIn(List<String> values) {
            addCriterion("userCode not in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("userCode between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("userCode not between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andRefereeIsNull() {
            addCriterion("referee is null");
            return (Criteria) this;
        }

        public Criteria andRefereeIsNotNull() {
            addCriterion("referee is not null");
            return (Criteria) this;
        }

        public Criteria andRefereeEqualTo(String value) {
            addCriterion("referee =", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotEqualTo(String value) {
            addCriterion("referee <>", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeGreaterThan(String value) {
            addCriterion("referee >", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeGreaterThanOrEqualTo(String value) {
            addCriterion("referee >=", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLessThan(String value) {
            addCriterion("referee <", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLessThanOrEqualTo(String value) {
            addCriterion("referee <=", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLike(String value) {
            addCriterion("referee like", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotLike(String value) {
            addCriterion("referee not like", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeIn(List<String> values) {
            addCriterion("referee in", values, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotIn(List<String> values) {
            addCriterion("referee not in", values, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeBetween(String value1, String value2) {
            addCriterion("referee between", value1, value2, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotBetween(String value1, String value2) {
            addCriterion("referee not between", value1, value2, "referee");
            return (Criteria) this;
        }

        public Criteria andUsrIdIsNull() {
            addCriterion("usrId is null");
            return (Criteria) this;
        }

        public Criteria andUsrIdIsNotNull() {
            addCriterion("usrId is not null");
            return (Criteria) this;
        }

        public Criteria andUsrIdEqualTo(String value) {
            addCriterion("usrId =", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotEqualTo(String value) {
            addCriterion("usrId <>", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdGreaterThan(String value) {
            addCriterion("usrId >", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdGreaterThanOrEqualTo(String value) {
            addCriterion("usrId >=", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdLessThan(String value) {
            addCriterion("usrId <", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdLessThanOrEqualTo(String value) {
            addCriterion("usrId <=", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdLike(String value) {
            addCriterion("usrId like", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotLike(String value) {
            addCriterion("usrId not like", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdIn(List<String> values) {
            addCriterion("usrId in", values, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotIn(List<String> values) {
            addCriterion("usrId not in", values, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdBetween(String value1, String value2) {
            addCriterion("usrId between", value1, value2, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotBetween(String value1, String value2) {
            addCriterion("usrId not between", value1, value2, "usrId");
            return (Criteria) this;
        }

        public Criteria andSourceFlagIsNull() {
            addCriterion("sourceFlag is null");
            return (Criteria) this;
        }

        public Criteria andSourceFlagIsNotNull() {
            addCriterion("sourceFlag is not null");
            return (Criteria) this;
        }

        public Criteria andSourceFlagEqualTo(String value) {
            addCriterion("sourceFlag =", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotEqualTo(String value) {
            addCriterion("sourceFlag <>", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagGreaterThan(String value) {
            addCriterion("sourceFlag >", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagGreaterThanOrEqualTo(String value) {
            addCriterion("sourceFlag >=", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagLessThan(String value) {
            addCriterion("sourceFlag <", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagLessThanOrEqualTo(String value) {
            addCriterion("sourceFlag <=", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagLike(String value) {
            addCriterion("sourceFlag like", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotLike(String value) {
            addCriterion("sourceFlag not like", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagIn(List<String> values) {
            addCriterion("sourceFlag in", values, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotIn(List<String> values) {
            addCriterion("sourceFlag not in", values, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagBetween(String value1, String value2) {
            addCriterion("sourceFlag between", value1, value2, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotBetween(String value1, String value2) {
            addCriterion("sourceFlag not between", value1, value2, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeIsNull() {
            addCriterion("inviterUserCode is null");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeIsNotNull() {
            addCriterion("inviterUserCode is not null");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeEqualTo(String value) {
            addCriterion("inviterUserCode =", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeNotEqualTo(String value) {
            addCriterion("inviterUserCode <>", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeGreaterThan(String value) {
            addCriterion("inviterUserCode >", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inviterUserCode >=", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeLessThan(String value) {
            addCriterion("inviterUserCode <", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeLessThanOrEqualTo(String value) {
            addCriterion("inviterUserCode <=", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeLike(String value) {
            addCriterion("inviterUserCode like", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeNotLike(String value) {
            addCriterion("inviterUserCode not like", value, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeIn(List<String> values) {
            addCriterion("inviterUserCode in", values, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeNotIn(List<String> values) {
            addCriterion("inviterUserCode not in", values, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeBetween(String value1, String value2) {
            addCriterion("inviterUserCode between", value1, value2, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andInviterUserCodeNotBetween(String value1, String value2) {
            addCriterion("inviterUserCode not between", value1, value2, "inviterUserCode");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdIsNull() {
            addCriterion("DifferentIndustryId is null");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdIsNotNull() {
            addCriterion("DifferentIndustryId is not null");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdEqualTo(Integer value) {
            addCriterion("DifferentIndustryId =", value, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdNotEqualTo(Integer value) {
            addCriterion("DifferentIndustryId <>", value, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdGreaterThan(Integer value) {
            addCriterion("DifferentIndustryId >", value, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DifferentIndustryId >=", value, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdLessThan(Integer value) {
            addCriterion("DifferentIndustryId <", value, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdLessThanOrEqualTo(Integer value) {
            addCriterion("DifferentIndustryId <=", value, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdIn(List<Integer> values) {
            addCriterion("DifferentIndustryId in", values, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdNotIn(List<Integer> values) {
            addCriterion("DifferentIndustryId not in", values, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdBetween(Integer value1, Integer value2) {
            addCriterion("DifferentIndustryId between", value1, value2, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andDifferentIndustryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DifferentIndustryId not between", value1, value2, "differentIndustryId");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagIsNull() {
            addCriterion("updateFlag is null");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagIsNotNull() {
            addCriterion("updateFlag is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagEqualTo(Short value) {
            addCriterion("updateFlag =", value, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagNotEqualTo(Short value) {
            addCriterion("updateFlag <>", value, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagGreaterThan(Short value) {
            addCriterion("updateFlag >", value, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("updateFlag >=", value, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagLessThan(Short value) {
            addCriterion("updateFlag <", value, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagLessThanOrEqualTo(Short value) {
            addCriterion("updateFlag <=", value, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagIn(List<Short> values) {
            addCriterion("updateFlag in", values, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagNotIn(List<Short> values) {
            addCriterion("updateFlag not in", values, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagBetween(Short value1, Short value2) {
            addCriterion("updateFlag between", value1, value2, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateFlagNotBetween(Short value1, Short value2) {
            addCriterion("updateFlag not between", value1, value2, "updateFlag");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_main
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 06 15:58:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_main
     *
     * @mbggenerated Wed Apr 06 15:58:15 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}